PROMPT='%B%F{black}[%c]%f%b > '

alias g='gcc -Wall -Werror -Wextra'
alias m='make'
alias mc='make clean'
alias mf='make fclean'
alias mr='make re'
alias n='norminette'
alias c='cat -e'
alias -g desk='~/Desktop/'
alias px='chmod u+x *.php'
